version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    open-pull-requests-limit: 0

  - package-ecosystem: 'nuget'
    directory: '/apps/auto'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 0

  - package-ecosystem: 'pip'
    directory: '/apps/api/search-svc'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 0

  - package-ecosystem: 'pip'
    directory: '/apps/api/chat-svc'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 0

  - package-ecosystem: 'pip'
    directory: '/apps/api/model'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 0