image:
    file: .gitpod.Dockerfile

tasks:
  - init: pnpm install -f

vscode:
  extensions:
    - "humao.rest-client"
    - "aaron-bond.better-comments"
    - "ms-azuretools.vscode-docker"
    - "wix.vscode-import-cost"
    - "dsznajder.es7-react-js-snippets"
    - "mikestead.dotenv"
    - "formulahendry.auto-complete-tag"
    - "SonarSource.sonarlint-vscode"
    - "christian-kohler.npm-intellisense"
    - "nrwl.angular-console"
    - "esbenp.prettier-vscode"
    - "dbaeumer.vscode-eslint"
