apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: auth-worker
spec:
  scaleTargetRef:
    deploymentName: auth-worker
  pollingInterval: 10
  cooldownPeriod: 30
  maxReplicaCount: 10
  triggers:
    - type: postgresql
      metadata:
        connection: cG9zdGdyZXM6Ly9hZG1pbjpodXRlY2gkMTIzQHBvc3RncmVzOjYwMDEvYXV0aF9zdmNfZGI=
