apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: law-worker
spec:
  scaleTargetRef:
    deploymentName: law-worker
  pollingInterval: 10
  cooldownPeriod: 30
  maxReplicaCount: 10
  triggers:
    - type: postgresql
      metadata:
        connection: cG9zdGdyZXM6Ly9hZG1pbjpodXRlY2gkMTIzQHBvc3RncmVzOjYwMDEvbGF3X3N2Y19kYg==
