apiVersion: v1
kind: Secret
metadata:
  name: chat-redis-secret
  namespace: default
type: Opaque
data:
  redis_password: cm9vdA==
---
apiVersion: keda.k8s.io/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-redis-secret
  namespace: default
spec:
  secretTargetRef:
    - parameter: password
      name: chat-redis-secret
      key: redis_password
---
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: redis-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    deploymentName: chat
  triggers:
    - type: redis
      metadata:
        address: REDIS_ADDRESS
        listName: chat
        listLength: "10"
      authenticationRef:
        name: keda-trigger-auth-redis-secret
