apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: search-db-job
spec:
  jobTargetRef:
    template:
      spec:
        containers:
          - name: mongodb
            image: mongo:latest
            imagePullPolicy: IfNotPresent
        restartPolicy: Never
    backoffLimit: 1
  maxReplicaCount: 30
  failedJobsHistoryLimit: 10
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: search-db-trigger-auth
spec:
  secretTargetRef:
    - parameter: connectionString
      name: mongodb-secret
      key: connect
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  connect: gqZ3ZWJzaXRlLWNvbm5lY3Rpb246Ly9hZG1pbjpodXRlY2gkMTIzQHBvc3RncmVzOjYwMDEvbW9uZ29kYg==
