backend:
  image:
    repository: ghcr.io/foxminchan/gateway
    tag: latest

  nameOverride: gateway
  fullnameOverride: gateway
  databaseName: gateway
  ingress:
    enabled: true
    host: api.hutech.dev.com
    path: /gateway
