backend:
  image:
    repository: ghcr.io/foxminchan/gateway
    tag: latest

  nameOverride: gateway
  fullnameOverride: gateway
  databaseName: gateway
  ingress:
    enabled: true
    host: api.hutech.dev.com
    path: /gateway

  resource:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
