backend:
  image:
    repository: ghcr.io/foxminchan/law-svc
    tag: latest

  nameOverride: law-svc
  fullnameOverride: law-svc
  databaseName: law-svc
  ingress:
    enabled: true
    host: api.hutech.dev.com
    path: /law-svc

  resource:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
