backend:
  image:
    repository: ghcr.io/foxminchan/chat-svc
    tag: latest

  nameOverride: chat-svc
  fullnameOverride: chat-svc
  databaseName: chat-svc
  ingress:
    enabled: true
    host: api.hutech.dev.com
    path: /chat-svc

  resource:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
