backend:
  image:
    repository: ghcr.io/foxminchan/auth-svc
    tag: latest

  nameOverride: auth-svc
  fullnameOverride: auth-svc
  databaseName: auth-svc
  ingress:
    enabled: true
    host: api.hutech.dev.com
    path: /auth-svc

  resource:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
