apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: daprconfig
  namespace: default
spec:
  template:
    metadata:
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "LawKnowledge"
        dapr.io/app-port: "8080"
        dapr.io/config: "appconfig"
